import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:google_fonts/google_fonts.dart';

import '../../../../app/theme.dart';
import '../../../../shared/models/payment_settings_model.dart';
import '../../widgets/admin_responsive_scaffold.dart';
import '../providers/payment_providers.dart';

class AdminPaymentSettingsScreen extends ConsumerStatefulWidget {
  const AdminPaymentSettingsScreen({super.key});

  @override
  ConsumerState<AdminPaymentSettingsScreen> createState() =>
      _AdminPaymentSettingsScreenState();
}

class _AdminPaymentSettingsScreenState
    extends ConsumerState<AdminPaymentSettingsScreen> {
  bool _loading = true;
  bool _saving = false;
  PaymentSettingsModel _settings = const PaymentSettingsModel();

  late final TextEditingController _monthlyCtrl;
  late final TextEditingController _admissionCtrl;
  late final TextEditingController _materialCtrl;
  late final TextEditingController _examCtrl;
  late final TextEditingController _specialCtrl;
  late final TextEditingController _fineCtrl;
  late final TextEditingController _dueDayCtrl;
  late final TextEditingController _autoDueDayCtrl;
  late final TextEditingController _bkashCtrl;
  late final TextEditingController _nagadCtrl;
  late final TextEditingController _bankCtrl;

  @override
  void initState() {
    super.initState();
    _monthlyCtrl = TextEditingController();
    _admissionCtrl = TextEditingController();
    _materialCtrl = TextEditingController();
    _examCtrl = TextEditingController();
    _specialCtrl = TextEditingController();
    _fineCtrl = TextEditingController();
    _dueDayCtrl = TextEditingController();
    _autoDueDayCtrl = TextEditingController();
    _bkashCtrl = TextEditingController();
    _nagadCtrl = TextEditingController();
    _bankCtrl = TextEditingController();
    _load();
  }

  @override
  void dispose() {
    _monthlyCtrl.dispose();
    _admissionCtrl.dispose();
    _materialCtrl.dispose();
    _examCtrl.dispose();
    _specialCtrl.dispose();
    _fineCtrl.dispose();
    _dueDayCtrl.dispose();
    _autoDueDayCtrl.dispose();
    _bkashCtrl.dispose();
    _nagadCtrl.dispose();
    _bankCtrl.dispose();
    super.dispose();
  }

  Future<void> _load() async {
    final s = await ref.read(paymentRepositoryProvider).getPaymentSettings();
    if (!mounted) return;
    setState(() {
      _settings = s;
      _monthlyCtrl.text = s.monthlyDefaultAmount.toStringAsFixed(2);
      _admissionCtrl.text = s.admissionDefaultAmount.toStringAsFixed(2);
      _materialCtrl.text = s.materialDefaultAmount.toStringAsFixed(2);
      _examCtrl.text = s.examDefaultAmount.toStringAsFixed(2);
      _specialCtrl.text = s.specialDefaultAmount.toStringAsFixed(2);
      _fineCtrl.text = s.fineDefaultAmount.toStringAsFixed(2);
      _dueDayCtrl.text = s.dueDayOfMonth.toString();
      _autoDueDayCtrl.text = s.autoGenerateDueDay.toString();
      _bkashCtrl.text = s.bkashNumber ?? '';
      _nagadCtrl.text = s.nagadNumber ?? '';
      _bankCtrl.text = s.bankDetails ?? '';
      _loading = false;
    });
  }

  double _num(TextEditingController c, double fallback) =>
      double.tryParse(c.text.trim()) ?? fallback;
  int _int(TextEditingController c, int fallback) =>
      int.tryParse(c.text.trim()) ?? fallback;

  Future<void> _save() async {
    setState(() => _saving = true);
    try {
      final payload = PaymentSettingsModel(
        monthlyDefaultAmount: _num(_monthlyCtrl, _settings.monthlyDefaultAmount),
        admissionDefaultAmount:
            _num(_admissionCtrl, _settings.admissionDefaultAmount),
        materialDefaultAmount: _num(_materialCtrl, _settings.materialDefaultAmount),
        examDefaultAmount: _num(_examCtrl, _settings.examDefaultAmount),
        specialDefaultAmount: _num(_specialCtrl, _settings.specialDefaultAmount),
        fineDefaultAmount: _num(_fineCtrl, _settings.fineDefaultAmount),
        dueDayOfMonth: _int(_dueDayCtrl, _settings.dueDayOfMonth).clamp(1, 31),
        autoGenerateDueDay:
            _int(_autoDueDayCtrl, _settings.autoGenerateDueDay).clamp(1, 31),
        acceptCash: _settings.acceptCash,
        acceptBkash: _settings.acceptBkash,
        acceptNagad: _settings.acceptNagad,
        acceptBank: _settings.acceptBank,
        acceptOther: _settings.acceptOther,
        bkashNumber: _bkashCtrl.text.trim().isEmpty ? null : _bkashCtrl.text.trim(),
        nagadNumber: _nagadCtrl.text.trim().isEmpty ? null : _nagadCtrl.text.trim(),
        bankDetails: _bankCtrl.text.trim().isEmpty ? null : _bankCtrl.text.trim(),
        voucherCenterName: _settings.voucherCenterName,
        voucherAddress: _settings.voucherAddress,
        voucherPhone: _settings.voucherPhone,
        voucherQrEnabled: _settings.voucherQrEnabled,
      );
      final saved = await ref.read(paymentRepositoryProvider).savePaymentSettings(payload);
      if (!mounted) return;
      setState(() {
        _settings = saved;
        _saving = false;
      });
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(content: Text('Payment settings saved', style: GoogleFonts.hindSiliguri())),
      );
    } catch (e) {
      if (!mounted) return;
      setState(() => _saving = false);
      ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text('$e')));
    }
  }

  Widget _amountField(String label, TextEditingController controller) {
    return TextField(
      controller: controller,
      keyboardType: const TextInputType.numberWithOptions(decimal: true),
      decoration: InputDecoration(
        labelText: label,
        border: OutlineInputBorder(borderRadius: BorderRadius.circular(AppTheme.cardRadius)),
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    return AdminResponsiveScaffold(
      title: Text('Payment Settings', style: GoogleFonts.hindSiliguri()),
      body: _loading
          ? const Center(child: CircularProgressIndicator())
          : ListView(
              padding: const EdgeInsets.all(16),
              children: [
                Text('Default amounts', style: GoogleFonts.hindSiliguri(fontWeight: FontWeight.w700)),
                const SizedBox(height: 10),
                _amountField('Monthly', _monthlyCtrl),
                const SizedBox(height: 8),
                _amountField('Admission', _admissionCtrl),
                const SizedBox(height: 8),
                _amountField('Material', _materialCtrl),
                const SizedBox(height: 8),
                _amountField('Exam', _examCtrl),
                const SizedBox(height: 8),
                _amountField('Special', _specialCtrl),
                const SizedBox(height: 8),
                _amountField('Fine', _fineCtrl),
                const SizedBox(height: 14),
                Text('Due generation', style: GoogleFonts.hindSiliguri(fontWeight: FontWeight.w700)),
                const SizedBox(height: 10),
                TextField(
                  controller: _dueDayCtrl,
                  keyboardType: TextInputType.number,
                  decoration: InputDecoration(
                    labelText: 'Due day of month (1-31)',
                    border: OutlineInputBorder(borderRadius: BorderRadius.circular(AppTheme.cardRadius)),
                  ),
                ),
                const SizedBox(height: 8),
                TextField(
                  controller: _autoDueDayCtrl,
                  keyboardType: TextInputType.number,
                  decoration: InputDecoration(
                    labelText: 'Auto due create day (1-31)',
                    border: OutlineInputBorder(borderRadius: BorderRadius.circular(AppTheme.cardRadius)),
                  ),
                ),
                const SizedBox(height: 14),
                Text('Accepted methods', style: GoogleFonts.hindSiliguri(fontWeight: FontWeight.w700)),
                SwitchListTile(
                  title: Text('Cash', style: GoogleFonts.hindSiliguri()),
                  value: _settings.acceptCash,
                  onChanged: (v) => setState(() => _settings = PaymentSettingsModel(
                    monthlyDefaultAmount: _settings.monthlyDefaultAmount,
                    admissionDefaultAmount: _settings.admissionDefaultAmount,
                    materialDefaultAmount: _settings.materialDefaultAmount,
                    examDefaultAmount: _settings.examDefaultAmount,
                    specialDefaultAmount: _settings.specialDefaultAmount,
                    fineDefaultAmount: _settings.fineDefaultAmount,
                    dueDayOfMonth: _settings.dueDayOfMonth,
                    autoGenerateDueDay: _settings.autoGenerateDueDay,
                    acceptCash: v,
                    acceptBkash: _settings.acceptBkash,
                    acceptNagad: _settings.acceptNagad,
                    acceptBank: _settings.acceptBank,
                    acceptOther: _settings.acceptOther,
                    bkashNumber: _settings.bkashNumber,
                    nagadNumber: _settings.nagadNumber,
                    bankDetails: _settings.bankDetails,
                    voucherCenterName: _settings.voucherCenterName,
                    voucherAddress: _settings.voucherAddress,
                    voucherPhone: _settings.voucherPhone,
                    voucherQrEnabled: _settings.voucherQrEnabled,
                  )),
                ),
                SwitchListTile(
                  title: Text('bKash', style: GoogleFonts.hindSiliguri()),
                  value: _settings.acceptBkash,
                  onChanged: (v) => setState(() => _settings = PaymentSettingsModel(
                    monthlyDefaultAmount: _settings.monthlyDefaultAmount,
                    admissionDefaultAmount: _settings.admissionDefaultAmount,
                    materialDefaultAmount: _settings.materialDefaultAmount,
                    examDefaultAmount: _settings.examDefaultAmount,
                    specialDefaultAmount: _settings.specialDefaultAmount,
                    fineDefaultAmount: _settings.fineDefaultAmount,
                    dueDayOfMonth: _settings.dueDayOfMonth,
                    autoGenerateDueDay: _settings.autoGenerateDueDay,
                    acceptCash: _settings.acceptCash,
                    acceptBkash: v,
                    acceptNagad: _settings.acceptNagad,
                    acceptBank: _settings.acceptBank,
                    acceptOther: _settings.acceptOther,
                    bkashNumber: _settings.bkashNumber,
                    nagadNumber: _settings.nagadNumber,
                    bankDetails: _settings.bankDetails,
                    voucherCenterName: _settings.voucherCenterName,
                    voucherAddress: _settings.voucherAddress,
                    voucherPhone: _settings.voucherPhone,
                    voucherQrEnabled: _settings.voucherQrEnabled,
                  )),
                ),
                SwitchListTile(
                  title: Text('Nagad', style: GoogleFonts.hindSiliguri()),
                  value: _settings.acceptNagad,
                  onChanged: (v) => setState(() => _settings = PaymentSettingsModel(
                    monthlyDefaultAmount: _settings.monthlyDefaultAmount,
                    admissionDefaultAmount: _settings.admissionDefaultAmount,
                    materialDefaultAmount: _settings.materialDefaultAmount,
                    examDefaultAmount: _settings.examDefaultAmount,
                    specialDefaultAmount: _settings.specialDefaultAmount,
                    fineDefaultAmount: _settings.fineDefaultAmount,
                    dueDayOfMonth: _settings.dueDayOfMonth,
                    autoGenerateDueDay: _settings.autoGenerateDueDay,
                    acceptCash: _settings.acceptCash,
                    acceptBkash: _settings.acceptBkash,
                    acceptNagad: v,
                    acceptBank: _settings.acceptBank,
                    acceptOther: _settings.acceptOther,
                    bkashNumber: _settings.bkashNumber,
                    nagadNumber: _settings.nagadNumber,
                    bankDetails: _settings.bankDetails,
                    voucherCenterName: _settings.voucherCenterName,
                    voucherAddress: _settings.voucherAddress,
                    voucherPhone: _settings.voucherPhone,
                    voucherQrEnabled: _settings.voucherQrEnabled,
                  )),
                ),
                SwitchListTile(
                  title: Text('Bank', style: GoogleFonts.hindSiliguri()),
                  value: _settings.acceptBank,
                  onChanged: (v) => setState(() => _settings = PaymentSettingsModel(
                    monthlyDefaultAmount: _settings.monthlyDefaultAmount,
                    admissionDefaultAmount: _settings.admissionDefaultAmount,
                    materialDefaultAmount: _settings.materialDefaultAmount,
                    examDefaultAmount: _settings.examDefaultAmount,
                    specialDefaultAmount: _settings.specialDefaultAmount,
                    fineDefaultAmount: _settings.fineDefaultAmount,
                    dueDayOfMonth: _settings.dueDayOfMonth,
                    autoGenerateDueDay: _settings.autoGenerateDueDay,
                    acceptCash: _settings.acceptCash,
                    acceptBkash: _settings.acceptBkash,
                    acceptNagad: _settings.acceptNagad,
                    acceptBank: v,
                    acceptOther: _settings.acceptOther,
                    bkashNumber: _settings.bkashNumber,
                    nagadNumber: _settings.nagadNumber,
                    bankDetails: _settings.bankDetails,
                    voucherCenterName: _settings.voucherCenterName,
                    voucherAddress: _settings.voucherAddress,
                    voucherPhone: _settings.voucherPhone,
                    voucherQrEnabled: _settings.voucherQrEnabled,
                  )),
                ),
                SwitchListTile(
                  title: Text('Other', style: GoogleFonts.hindSiliguri()),
                  value: _settings.acceptOther,
                  onChanged: (v) => setState(() => _settings = PaymentSettingsModel(
                    monthlyDefaultAmount: _settings.monthlyDefaultAmount,
                    admissionDefaultAmount: _settings.admissionDefaultAmount,
                    materialDefaultAmount: _settings.materialDefaultAmount,
                    examDefaultAmount: _settings.examDefaultAmount,
                    specialDefaultAmount: _settings.specialDefaultAmount,
                    fineDefaultAmount: _settings.fineDefaultAmount,
                    dueDayOfMonth: _settings.dueDayOfMonth,
                    autoGenerateDueDay: _settings.autoGenerateDueDay,
                    acceptCash: _settings.acceptCash,
                    acceptBkash: _settings.acceptBkash,
                    acceptNagad: _settings.acceptNagad,
                    acceptBank: _settings.acceptBank,
                    acceptOther: v,
                    bkashNumber: _settings.bkashNumber,
                    nagadNumber: _settings.nagadNumber,
                    bankDetails: _settings.bankDetails,
                    voucherCenterName: _settings.voucherCenterName,
                    voucherAddress: _settings.voucherAddress,
                    voucherPhone: _settings.voucherPhone,
                    voucherQrEnabled: _settings.voucherQrEnabled,
                  )),
                ),
                const SizedBox(height: 12),
                TextField(
                  controller: _bkashCtrl,
                  decoration: InputDecoration(
                    labelText: 'bKash Number',
                    border: OutlineInputBorder(borderRadius: BorderRadius.circular(AppTheme.cardRadius)),
                  ),
                ),
                const SizedBox(height: 8),
                TextField(
                  controller: _nagadCtrl,
                  decoration: InputDecoration(
                    labelText: 'Nagad Number',
                    border: OutlineInputBorder(borderRadius: BorderRadius.circular(AppTheme.cardRadius)),
                  ),
                ),
                const SizedBox(height: 8),
                TextField(
                  controller: _bankCtrl,
                  maxLines: 2,
                  decoration: InputDecoration(
                    labelText: 'Bank details',
                    border: OutlineInputBorder(borderRadius: BorderRadius.circular(AppTheme.cardRadius)),
                  ),
                ),
                const SizedBox(height: 16),
                FilledButton(
                  onPressed: _saving ? null : _save,
                  child: Text(_saving ? 'Saving...' : 'Save settings', style: GoogleFonts.hindSiliguri()),
                ),
              ],
            ),
    );
  }
}
