import 'payment_model.dart';

class PaymentSettingsModel {
  const PaymentSettingsModel({
    this.monthlyDefaultAmount = 1500,
    this.admissionDefaultAmount = 500,
    this.materialDefaultAmount = 300,
    this.examDefaultAmount = 100,
    this.specialDefaultAmount = 0,
    this.fineDefaultAmount = 0,
    this.dueDayOfMonth = 15,
    this.autoGenerateDueDay = 1,
    this.acceptCash = true,
    this.acceptBkash = true,
    this.acceptNagad = true,
    this.acceptBank = true,
    this.acceptOther = true,
    this.bkashNumber,
    this.nagadNumber,
    this.bankDetails,
    this.voucherCenterName = 'Radiance Coaching Center',
    this.voucherAddress,
    this.voucherPhone,
    this.voucherQrEnabled = true,
  });

  final double monthlyDefaultAmount;
  final double admissionDefaultAmount;
  final double materialDefaultAmount;
  final double examDefaultAmount;
  final double specialDefaultAmount;
  final double fineDefaultAmount;
  final int dueDayOfMonth;
  final int autoGenerateDueDay;
  final bool acceptCash;
  final bool acceptBkash;
  final bool acceptNagad;
  final bool acceptBank;
  final bool acceptOther;
  final String? bkashNumber;
  final String? nagadNumber;
  final String? bankDetails;
  final String voucherCenterName;
  final String? voucherAddress;
  final String? voucherPhone;
  final bool voucherQrEnabled;

  factory PaymentSettingsModel.fromJson(Map<String, dynamic> json) {
    return PaymentSettingsModel(
      monthlyDefaultAmount: _d(json['monthly_default_amount'], 1500),
      admissionDefaultAmount: _d(json['admission_default_amount'], 500),
      materialDefaultAmount: _d(json['material_default_amount'], 300),
      examDefaultAmount: _d(json['exam_default_amount'], 100),
      specialDefaultAmount: _d(json['special_default_amount'], 0),
      fineDefaultAmount: _d(json['fine_default_amount'], 0),
      dueDayOfMonth: (json['due_day_of_month'] as int?) ?? 15,
      autoGenerateDueDay: (json['auto_generate_due_day'] as int?) ?? 1,
      acceptCash: json['accept_cash'] as bool? ?? true,
      acceptBkash: json['accept_bkash'] as bool? ?? true,
      acceptNagad: json['accept_nagad'] as bool? ?? true,
      acceptBank: json['accept_bank'] as bool? ?? true,
      acceptOther: json['accept_other'] as bool? ?? true,
      bkashNumber: json['bkash_number'] as String?,
      nagadNumber: json['nagad_number'] as String?,
      bankDetails: json['bank_details'] as String?,
      voucherCenterName:
          json['voucher_center_name'] as String? ?? 'Radiance Coaching Center',
      voucherAddress: json['voucher_address'] as String?,
      voucherPhone: json['voucher_phone'] as String?,
      voucherQrEnabled: json['voucher_qr_enabled'] as bool? ?? true,
    );
  }

  Map<String, dynamic> toUpsertJson({String? updatedBy}) {
    return <String, dynamic>{
      'singleton_key': 1,
      'monthly_default_amount': monthlyDefaultAmount,
      'admission_default_amount': admissionDefaultAmount,
      'material_default_amount': materialDefaultAmount,
      'exam_default_amount': examDefaultAmount,
      'special_default_amount': specialDefaultAmount,
      'fine_default_amount': fineDefaultAmount,
      'due_day_of_month': dueDayOfMonth,
      'auto_generate_due_day': autoGenerateDueDay,
      'accept_cash': acceptCash,
      'accept_bkash': acceptBkash,
      'accept_nagad': acceptNagad,
      'accept_bank': acceptBank,
      'accept_other': acceptOther,
      'bkash_number': bkashNumber,
      'nagad_number': nagadNumber,
      'bank_details': bankDetails,
      'voucher_center_name': voucherCenterName,
      'voucher_address': voucherAddress,
      'voucher_phone': voucherPhone,
      'voucher_qr_enabled': voucherQrEnabled,
      'updated_at': DateTime.now().toUtc().toIso8601String(),
      'updated_by': updatedBy,
    };
  }

  double defaultAmountForCode(String code, {double fallback = 0}) {
    switch (code.toLowerCase()) {
      case 'monthly':
        return monthlyDefaultAmount;
      case 'admission':
        return admissionDefaultAmount;
      case 'material':
        return materialDefaultAmount;
      case 'exam':
        return examDefaultAmount;
      case 'special':
        return specialDefaultAmount;
      case 'fine':
        return fineDefaultAmount;
      default:
        return fallback;
    }
  }

  List<PaymentMethod> allowedMethods() {
    final out = <PaymentMethod>[];
    if (acceptCash) out.add(PaymentMethod.cash);
    if (acceptBkash) out.add(PaymentMethod.bkash);
    if (acceptNagad) out.add(PaymentMethod.nagad);
    if (acceptBank) out.add(PaymentMethod.bank);
    if (acceptOther) out.add(PaymentMethod.other);
    if (out.isEmpty) out.add(PaymentMethod.cash);
    return out;
  }
}

double _d(dynamic v, double fallback) {
  if (v is num) return v.toDouble();
  if (v is String) return double.tryParse(v) ?? fallback;
  return fallback;
}
